= Platform Documentation
Ulli Schaechtle <u.schaechtle@gmail.com>

This site hosts technical documentation for the InferenceQL platform.

== Disclaimer

**InferenceQL is pre-alpha / unreleased software.** There are known and unknown isues and bugs. Crashes are expected.  This software should not be expected to treat your data securely.

== Content

Welcome to our first attempt to document the InferenceQL platform. The
documentation covers:

* xref:structure-learning::quick-start.adoc[Quickstart]

* xref:structure-learning::structure-learning.adoc[Structure learning]

* Inference Query language
** xref:query::iql-permissive.adoc[Query language (IQL-permissive)]
** xref:query::iql-permissive.adoc[Research Query Language -- aimed at PL researchers (IQL-permissive)]

We recommend all users begin with the xref:structure-learning::quick-start.adoc[Quickstart] tutorial.

== Open-source code

Please find our open source code https://github.com/OpenIQL[here].

== Citation

Please cite this work as: Ulrich Schaechtle, Cameron Freer, Zane Shelby, Feras Saad, and Vikash Mansinghka. "Bayesian
AutoML for Databases via the InferenceQL Probabilistic Programming System."
AutoML Conference 2022 - Workshop Track. Find the PDF https://2022.automl.cc/wp-content/uploads/2022/07/bayesian_automl_for_databases_.pdf[here].

== License

All of InferenceQL is open source and licensed under Apache 2.0. At times, the
InferenceQL teams maintains private repos hosting components of InferenceQL to
prepare an OSS release. If you happen to have privileged private access -
please don't share it pre-release.


